// ============================================================================
// MotoGo — Marka Veritabanı
// ============================================================================
// "info" alanı şimdilik boş — zamanla (menşei, üretim yılı, ülke gibi)
// kısa bilgiler eklenecek. Firma yok demek "henüz üye yok" demek, arama
// yine de çalışır.

const BRANDS = [
  { key: "abush", name: "Abush" },
  { key: "aeon", name: "Aeon" },
  { key: "altai", name: "Altai" },
  { key: "apachi", name: "Apachi" },
  { key: "apec", name: "Apec" },
  { key: "aprilia", name: "Aprilia" },
  { key: "ariic", name: "Ariic" },
  { key: "arnica", name: "Arnica" },
  { key: "arora", name: "Arora" },
  { key: "asya_motor", name: "Asya Motor" },
  { key: "bajaj", name: "Bajaj" },
  { key: "baotian", name: "Baotian" },
  { key: "barossa", name: "Barossa" },
  { key: "belderia", name: "Belderia" },
  { key: "benda_motor", name: "Benda Motor" },
  { key: "benelli", name: "Benelli" },
  { key: "beta", name: "Beta" },
  { key: "better", name: "Better" },
  { key: "bianchi", name: "Bianchi" },
  { key: "bisan", name: "Bisan" },
  { key: "bmw", name: "BMW" },
  { key: "boom", name: "Boom" },
  { key: "borelli_ledow", name: "Borelli Ledow" },
  { key: "brixton", name: "Brixton" },
  { key: "bsa", name: "BSA" },
  { key: "bumoto_jinling", name: "BuMoto/jinling" },
  { key: "can_am", name: "Can-Am" },
  { key: "cfmoto", name: "CFmoto" },
  { key: "crn", name: "CRN" },
  { key: "csn_motor", name: "CSN Motor" },
  { key: "daelim", name: "Daelim" },
  { key: "dayun", name: "Dayun" },
  { key: "delta_motorcycle", name: "Delta Motorcycle" },
  { key: "derbi", name: "Derbi" },
  { key: "dofern", name: "Dofern" },
  { key: "doohan", name: "Doohan" },
  { key: "ducati", name: "Ducati" },
  { key: "enbest", name: "Enbest" },
  { key: "falcon", name: "Falcon" },
  { key: "fantic", name: "Fantic" },
  { key: "fcm", name: "FCM" },
  { key: "fengchi", name: "Fengchi" },
  { key: "fym", name: "FYM" },
  { key: "gasgas", name: "GasGas" },
  { key: "gilera", name: "Gilera" },
  { key: "haojin", name: "Haojin" },
  { key: "haojue", name: "Haojue" },
  { key: "harley_davidson", name: "Harley-Davidson" },
  { key: "harput", name: "Harput" },
  { key: "hero", name: "Hero" },
  { key: "honda", name: "Honda" },
  { key: "husaberg", name: "Husaberg" },
  { key: "husqvarna", name: "Husqvarna" },
  { key: "hyosung", name: "Hyosung" },
  { key: "indian", name: "Indian" },
  { key: "italjet", name: "Italjet" },
  { key: "izh", name: "IZH" },
  { key: "jawa", name: "Jawa" },
  { key: "jiajue", name: "Jiajue" },
  { key: "jinding", name: "Jinding" },
  { key: "jinlun", name: "Jinlun" },
  { key: "jpn_motor", name: "JPN Motor" },
  { key: "jy_moto", name: "JY Moto" },
  { key: "kadirga", name: "Kadırga" },
  { key: "kamax", name: "Kamax" },
  { key: "kangda", name: "Kangda" },
  { key: "kanuni", name: "Kanuni" },
  { key: "kawasaki", name: "Kawasaki" },
  { key: "kayo_moto", name: "Kayo Moto" },
  { key: "keeway", name: "Keeway" },
  { key: "kimmi", name: "Kimmi" },
  { key: "kinetic", name: "Kinetic" },
  { key: "kinroad", name: "Kinroad" },
  { key: "kms", name: "KMS" },
  { key: "kove", name: "Kove" },
  { key: "kral_motor", name: "Kral Motor" },
  { key: "ktm", name: "KTM" },
  { key: "kuba", name: "Kuba" },
  { key: "kymco", name: "Kymco" },
  { key: "lambretta", name: "Lambretta" },
  { key: "leksas", name: "Leksas" },
  { key: "lifan", name: "Lifan" },
  { key: "lml", name: "LML" },
  { key: "loncin", name: "Loncin" },
  { key: "malaguti", name: "Malaguti" },
  { key: "maranta", name: "Maranta" },
  { key: "megelli", name: "Megelli" },
  { key: "meka_motor", name: "Meka Motor" },
  { key: "memnun", name: "Memnun" },
  { key: "minsk", name: "Minsk" },
  { key: "mobylette", name: "Mobylette" },
  { key: "modenas", name: "Modenas" },
  { key: "mondial", name: "Mondial" },
  { key: "moto_guzzi", name: "Moto Guzzi" },
  { key: "motolux", name: "Motolux" },
  { key: "moto_morini", name: "Moto Morini" },
  { key: "motoran", name: "Motoran" },
  { key: "motosan", name: "Motosan" },
  { key: "motozeus", name: "Motozeus" },
  { key: "musatti", name: "Musatti" },
  { key: "mutt", name: "Mutt" },
  { key: "mv_agusta", name: "MV Agusta" },
  { key: "mz", name: "MZ" },
  { key: "nanok", name: "Nanok" },
  { key: "ningbo_longjia", name: "Ningbo Longjia" },
  { key: "ohvale", name: "Ohvale" },
  { key: "omi", name: "OMİ" },
  { key: "peugeot", name: "Peugeot" },
  { key: "piaggio", name: "Piaggio" },
  { key: "pioneer", name: "Pioneer" },
  { key: "polaris", name: "Polaris" },
  { key: "presto", name: "Presto" },
  { key: "puch", name: "Puch" },
  { key: "qj", name: "QJ" },
  { key: "qooder", name: "Qooder" },
  { key: "ramzey", name: "Ramzey" },
  { key: "rasler", name: "Rasler" },
  { key: "rebat_motor", name: "Rebat Motor" },
  { key: "regal_raptor", name: "Regal Raptor" },
  { key: "revolt", name: "Revolt" },
  { key: "rewaco", name: "Rewaco" },
  { key: "rialli", name: "Rialli" },
  { key: "rieju", name: "Rieju" },
  { key: "rkn", name: "RKN" },
  { key: "rks", name: "RKS" },
  { key: "rmg_moto_gusto", name: "RMG Moto Gusto" },
  { key: "royal_alloy", name: "Royal Alloy" },
  { key: "royal_enfield", name: "Royal Enfield" },
  { key: "rutec", name: "Rutec" },
  { key: "salcano", name: "Salcano" },
  { key: "sam_motor", name: "Sam Motor" },
  { key: "seger", name: "Seger" },
  { key: "sfm", name: "SFM" },
  { key: "shenke", name: "Shenke" },
  { key: "sherco", name: "Sherco" },
  { key: "shinari", name: "Shinari" },
  { key: "simson", name: "Simson" },
  { key: "ski_doo", name: "Ski-doo" },
  { key: "skyjet", name: "Skyjet" },
  { key: "skyteam", name: "Skyteam" },
  { key: "spada", name: "Spada" },
  { key: "stmax", name: "Stmax" },
  { key: "superking", name: "Superking" },
  { key: "suzuki", name: "Suzuki" },
  { key: "swm", name: "SWM" },
  { key: "sym", name: "SYM" },
  { key: "taktas_motor", name: "Taktas Motor" },
  { key: "telstar", name: "Telstar" },
  { key: "texas", name: "Texas" },
  { key: "tgb", name: "TGB" },
  { key: "tm_racing", name: "TM Racing" },
  { key: "togo", name: "Togo" },
  { key: "triumph", name: "Triumph" },
  { key: "truva", name: "Truva" },
  { key: "tt", name: "TT" },
  { key: "tvs", name: "TVS" },
  { key: "ugursam", name: "UğurSam" },
  { key: "um", name: "UM" },
  { key: "ural", name: "Ural" },
  { key: "vespa", name: "Vespa" },
  { key: "victory", name: "Victory" },
  { key: "vitello", name: "Vitello" },
  { key: "voge", name: "Voge" },
  { key: "volta", name: "Volta" },
  { key: "voskhod", name: "Voskhod" },
  { key: "wlf", name: "WLF" },
  { key: "xgjao", name: "Xgjao" },
  { key: "xingyue", name: "Xingyue" },
  { key: "xintian", name: "Xintian" },
  { key: "yamaha", name: "Yamaha" },
  { key: "yiben", name: "Yiben" },
  { key: "yiying", name: "Yiying" },
  { key: "yuan", name: "Yuan" },
  { key: "yuki", name: "Yuki" },
  { key: "zealsun", name: "Zealsun" },
  { key: "zelsun", name: "Zelsun" },
  { key: "znen", name: "Znen" },
  { key: "zongshen", name: "Zongshen" },
  { key: "zontes", name: "Zontes" },
  { key: "zorro", name: "Zorro" },
];

// Her markanın altındaki alt kategoriler (Yol Yardım hariç, o markaya özel
// değil, ortak MotoGo Yol Yardım sistemine yönlendirir)
const SUBCATS = [
  { key: "ozelServis", label: "Özel Servis" },
  { key: "yetkiliServis", label: "Yetkili Servis" },
  { key: "yedekParca", label: "Yedek Parça" },
  { key: "ekspertiz", label: "Ekspertiz" },
  { key: "kiralik", label: "Kiralık Motor" },
  { key: "avantaj", label: "Avantajlı Firmalar" },
];

// Marka + alt kategoriye göre üye firmalar. Şimdilik boş, doldukça eklenir.
// Format: "markaKey_altKategoriKey": [ { name, whatsapp, city, instagram... } ]
const BRAND_FIRMS = {
  "cfmoto_yetkiliServis": [{ name: "Bayhas Motors", whatsapp: "905076045923", phone: "+905076045923", city: "Ankara", district: "Etimesgut, Gölbaşı, Polatlı, Yenimahalle, Kahramankazan", instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/" }],
  "cfmoto_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "cfmoto_yedekParca": [{ name: "Bayhas Motors", whatsapp: "905076045923", phone: "+905076045923", city: "Ankara", district: "Etimesgut, Gölbaşı, Polatlı, Yenimahalle, Kahramankazan", instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/" }],
  "cfmoto_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],

  "tvs_yetkiliServis": [{ name: "Bayhas Motors", whatsapp: "905076045923", phone: "+905076045923", city: "Ankara", district: "Etimesgut, Gölbaşı, Polatlı, Yenimahalle, Kahramankazan", instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/" }],
  "tvs_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "tvs_yedekParca": [{ name: "Bayhas Motors", whatsapp: "905076045923", phone: "+905076045923", city: "Ankara", district: "Etimesgut, Gölbaşı, Polatlı, Yenimahalle, Kahramankazan", instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/" }],
  "tvs_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],

  "mondial_yetkiliServis": [{ name: "Bayhas Motors", whatsapp: "905076045923", phone: "+905076045923", city: "Ankara", district: "Etimesgut, Gölbaşı, Polatlı, Yenimahalle, Kahramankazan", instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/" }],
  "mondial_yedekParca": [{ name: "Bayhas Motors", whatsapp: "905076045923", phone: "+905076045923", city: "Ankara", district: "Etimesgut, Gölbaşı, Polatlı, Yenimahalle, Kahramankazan", instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/" }],

  "sym_ozelServis": [{ name: "Duran Motor", whatsapp: "905433551273", phone: "+905433551273", city: "Ankara", district: "Etimesgut", instagram: "https://www.instagram.com/duranmotor06/" }],
  "sym_yedekParca": [{ name: "Duran Motor", whatsapp: "905433551273", phone: "+905433551273", city: "Ankara", district: "Etimesgut", instagram: "https://www.instagram.com/duranmotor06/" }],

  "bmw_ozelServis": [{ name: "Duran Motor", whatsapp: "905433551273", phone: "+905433551273", city: "Ankara", district: "Etimesgut", instagram: "https://www.instagram.com/duranmotor06/" }],
  "bmw_yedekParca": [{ name: "Duran Motor", whatsapp: "905433551273", phone: "+905433551273", city: "Ankara", district: "Etimesgut", instagram: "https://www.instagram.com/duranmotor06/" }],

  "yamaha_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "yamaha_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "honda_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "honda_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "jawa_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "jawa_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "kove_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "kove_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "arora_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "arora_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "kanuni_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "kanuni_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "keeway_ozelServis": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],
  "keeway_kiralik": [{ name: "Uluer Motor", whatsapp: "905051162247", phone: "+905051162247", city: "Ankara", district: "Batıkent", description: "Motor mekanik ve tamir bakım servisi - Kiralık", instagram: "https://www.instagram.com/uluermotors/" }],

  // Yeni firma eklerken bu formatta ekle (instagram/youtube/website/district/
  // description/photo OPSİYONEL):
  // "markaKey_altKategoriKey": [
  //   { name: "Firma Adı", whatsapp: "905XXXXXXXXX", city: "Ankara", district: "Etimesgut",
  //     description: "Kısa firma açıklaması", photo: "img/firma-foto.jpg",
  //     instagram: "https://instagram.com/..." }
  // ],
};

// Büyük şehirler önce, sonra alfabetik
const CITIES = [
  "İstanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep",
  "Kocaeli", "Mersin",
  "Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ardahan","Artvin","Aydın",
  "Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur",
  "Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ",
  "Erzincan","Erzurum","Eskişehir","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır",
  "Isparta","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri",
  "Kırıkkale","Kırklareli","Kırşehir","Kilis","Kütahya","Malatya","Manisa","Mardin",
  "Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun",
  "Siirt","Sinop","Sivas","Şanlıurfa","Şırnak","Tekirdağ","Tokat","Trabzon","Tunceli",
  "Uşak","Van","Yalova","Yozgat","Zonguldak"
];

// ============================================================================
// MotoGo Yol Yardım — eski siteyle birebir aynı veri, artık bu sayfanın içinde
// ============================================================================
const YARDIM_CATEGORIES = [
  { id: "cekici",      label: "Çekici / Transfer", sub: "Motor çalışmıyor / kaza",  icon: "🚛" },
  { id: "lastik",      label: "Lastik",            sub: "Patlak / hava kaybı",      icon: "🛞" },
  { id: "genel_ariza", label: "Genel Arıza",       sub: "Diğer teknik sorun",       icon: "🔧" }
];

const YARDIM_FIRMS = [
  {
    name: "Duran Motor",
    region: "Etimesgut, Ankara · Tüm Marka & BMW Özel Servis · SYM Yetkili Bayi",
    phone: "+905433551273",
    whatsapp: "905433551273",
    lat: 39.948151,
    lng: 32.645496,
    categories: ["aku_mars", "genel_ariza"],
    website: "https://duranmotor.com",
    instagram: "https://www.instagram.com/duranmotor06/"
  },
  {
    name: "Bayhas Motors",
    region: "Yenimahalle, Ankara · CF Moto Yetkili Servis",
    phone: "+905076045923",
    whatsapp: "905076045923",
    lat: 39.988424,
    lng: 32.663031,
    categories: ["aku_mars", "genel_ariza"],
    website: "https://www.bayhasmotors.com.tr",
    instagram: "https://www.instagram.com/bayhasmotorsyenimahalle/"
  },
  {
    name: "Uluer Motor",
    region: "Batıkent, Ankara · Motor Mekanik ve Tamir Servisi · Kiralama",
    phone: "+905051162247",
    whatsapp: "905051162247",
    lat: 39.9767,
    lng: 32.7625,
    categories: ["aku_mars", "genel_ariza"],
    description: "Motor mekanik ve tamir bakım servisi - Kiralık",
    instagram: "https://www.instagram.com/uluermotors/"
  },
];
