// ============================================================================
// MotoGo — Marka Veritabanı
// ============================================================================
// "info" alanı şimdilik boş — zamanla (menşei, üretim yılı, ülke gibi)
// kısa bilgiler eklenecek. Firma yok demek "henüz üye yok" demek, arama
// yine de çalışır.

const BRANDS = [
  { key: "abush", name: "Abush" },
  { key: "aeon", name: "Aeon" },
  { key: "altai", name: "Altai" },
  { key: "apachi", name: "Apachi" },
  { key: "apec", name: "Apec" },
  { key: "aprilia", name: "Aprilia" },
  { key: "ariic", name: "Ariic" },
  { key: "arnica", name: "Arnica" },
  { key: "arora", name: "Arora" },
  { key: "asya_motor", name: "Asya Motor" },
  { key: "bajaj", name: "Bajaj" },
  { key: "baotian", name: "Baotian" },
  { key: "barossa", name: "Barossa" },
  { key: "belderia", name: "Belderia" },
  { key: "benda_motor", name: "Benda Motor" },
  { key: "benelli", name: "Benelli" },
  { key: "beta", name: "Beta" },
  { key: "better", name: "Better" },
  { key: "bianchi", name: "Bianchi" },
  { key: "bisan", name: "Bisan" },
  { key: "bmw", name: "BMW" },
  { key: "boom", name: "Boom" },
  { key: "borelli_ledow", name: "Borelli Ledow" },
  { key: "brixton", name: "Brixton" },
  { key: "bsa", name: "BSA" },
  { key: "bumoto_jinling", name: "BuMoto/jinling" },
  { key: "can_am", name: "Can-Am" },
  { key: "cfmoto", name: "CFmoto" },
  { key: "crn", name: "CRN" },
  { key: "csn_motor", name: "CSN Motor" },
  { key: "daelim", name: "Daelim" },
  { key: "dayun", name: "Dayun" },
  { key: "delta_motorcycle", name: "Delta Motorcycle" },
  { key: "derbi", name: "Derbi" },
  { key: "dofern", name: "Dofern" },
  { key: "doohan", name: "Doohan" },
  { key: "ducati", name: "Ducati" },
  { key: "enbest", name: "Enbest" },
  { key: "falcon", name: "Falcon" },
  { key: "fantic", name: "Fantic" },
  { key: "fcm", name: "FCM" },
  { key: "fengchi", name: "Fengchi" },
  { key: "fym", name: "FYM" },
  { key: "gasgas", name: "GasGas" },
  { key: "gilera", name: "Gilera" },
  { key: "haojin", name: "Haojin" },
  { key: "haojue", name: "Haojue" },
  { key: "harley_davidson", name: "Harley-Davidson" },
  { key: "harput", name: "Harput" },
  { key: "hero", name: "Hero" },
  { key: "honda", name: "Honda" },
  { key: "husaberg", name: "Husaberg" },
  { key: "husqvarna", name: "Husqvarna" },
  { key: "hyosung", name: "Hyosung" },
  { key: "indian", name: "Indian" },
  { key: "italjet", name: "Italjet" },
  { key: "izh", name: "IZH" },
  { key: "jawa", name: "Jawa" },
  { key: "jiajue", name: "Jiajue" },
  { key: "jinding", name: "Jinding" },
  { key: "jinlun", name: "Jinlun" },
  { key: "jpn_motor", name: "JPN Motor" },
  { key: "jy_moto", name: "JY Moto" },
  { key: "kadirga", name: "Kadırga" },
  { key: "kamax", name: "Kamax" },
  { key: "kangda", name: "Kangda" },
  { key: "kanuni", name: "Kanuni" },
  { key: "kawasaki", name: "Kawasaki" },
  { key: "kayo_moto", name: "Kayo Moto" },
  { key: "keeway", name: "Keeway" },
  { key: "kimmi", name: "Kimmi" },
  { key: "kinetic", name: "Kinetic" },
  { key: "kinroad", name: "Kinroad" },
  { key: "kms", name: "KMS" },
  { key: "kove", name: "Kove" },
  { key: "kral_motor", name: "Kral Motor" },
  { key: "ktm", name: "KTM" },
  { key: "kuba", name: "Kuba" },
  { key: "kymco", name: "Kymco" },
  { key: "lambretta", name: "Lambretta" },
  { key: "leksas", name: "Leksas" },
  { key: "lifan", name: "Lifan" },
  { key: "lml", name: "LML" },
  { key: "loncin", name: "Loncin" },
  { key: "malaguti", name: "Malaguti" },
  { key: "maranta", name: "Maranta" },
  { key: "megelli", name: "Megelli" },
  { key: "meka_motor", name: "Meka Motor" },
  { key: "memnun", name: "Memnun" },
  { key: "minsk", name: "Minsk" },
  { key: "mobylette", name: "Mobylette" },
  { key: "modenas", name: "Modenas" },
  { key: "mondial", name: "Mondial" },
  { key: "moto_guzzi", name: "Moto Guzzi" },
  { key: "motolux", name: "Motolux" },
  { key: "moto_morini", name: "Moto Morini" },
  { key: "motoran", name: "Motoran" },
  { key: "motosan", name: "Motosan" },
  { key: "motozeus", name: "Motozeus" },
  { key: "musatti", name: "Musatti" },
  { key: "mutt", name: "Mutt" },
  { key: "mv_agusta", name: "MV Agusta" },
  { key: "mz", name: "MZ" },
  { key: "nanok", name: "Nanok" },
  { key: "ningbo_longjia", name: "Ningbo Longjia" },
  { key: "ohvale", name: "Ohvale" },
  { key: "omi", name: "OMİ" },
  { key: "peugeot", name: "Peugeot" },
  { key: "piaggio", name: "Piaggio" },
  { key: "pioneer", name: "Pioneer" },
  { key: "polaris", name: "Polaris" },
  { key: "presto", name: "Presto" },
  { key: "puch", name: "Puch" },
  { key: "qj", name: "QJ" },
  { key: "qooder", name: "Qooder" },
  { key: "ramzey", name: "Ramzey" },
  { key: "rasler", name: "Rasler" },
  { key: "rebat_motor", name: "Rebat Motor" },
  { key: "regal_raptor", name: "Regal Raptor" },
  { key: "revolt", name: "Revolt" },
  { key: "rewaco", name: "Rewaco" },
  { key: "rialli", name: "Rialli" },
  { key: "rieju", name: "Rieju" },
  { key: "rkn", name: "RKN" },
  { key: "rks", name: "RKS" },
  { key: "rmg_moto_gusto", name: "RMG Moto Gusto" },
  { key: "royal_alloy", name: "Royal Alloy" },
  { key: "royal_enfield", name: "Royal Enfield" },
  { key: "rutec", name: "Rutec" },
  { key: "salcano", name: "Salcano" },
  { key: "sam_motor", name: "Sam Motor" },
  { key: "seger", name: "Seger" },
  { key: "sfm", name: "SFM" },
  { key: "shenke", name: "Shenke" },
  { key: "sherco", name: "Sherco" },
  { key: "shinari", name: "Shinari" },
  { key: "simson", name: "Simson" },
  { key: "ski_doo", name: "Ski-doo" },
  { key: "skyjet", name: "Skyjet" },
  { key: "skyteam", name: "Skyteam" },
  { key: "spada", name: "Spada" },
  { key: "stmax", name: "Stmax" },
  { key: "superking", name: "Superking" },
  { key: "suzuki", name: "Suzuki" },
  { key: "swm", name: "SWM" },
  { key: "sym", name: "SYM" },
  { key: "taktas_motor", name: "Taktas Motor" },
  { key: "telstar", name: "Telstar" },
  { key: "texas", name: "Texas" },
  { key: "tgb", name: "TGB" },
  { key: "tm_racing", name: "TM Racing" },
  { key: "togo", name: "Togo" },
  { key: "triumph", name: "Triumph" },
  { key: "truva", name: "Truva" },
  { key: "tt", name: "TT" },
  { key: "tvs", name: "TVS" },
  { key: "ugursam", name: "UğurSam" },
  { key: "um", name: "UM" },
  { key: "ural", name: "Ural" },
  { key: "vespa", name: "Vespa" },
  { key: "victory", name: "Victory" },
  { key: "vitello", name: "Vitello" },
  { key: "voge", name: "Voge" },
  { key: "volta", name: "Volta" },
  { key: "voskhod", name: "Voskhod" },
  { key: "wlf", name: "WLF" },
  { key: "xgjao", name: "Xgjao" },
  { key: "xingyue", name: "Xingyue" },
  { key: "xintian", name: "Xintian" },
  { key: "yamaha", name: "Yamaha" },
  { key: "yiben", name: "Yiben" },
  { key: "yiying", name: "Yiying" },
  { key: "yuan", name: "Yuan" },
  { key: "yuki", name: "Yuki" },
  { key: "zealsun", name: "Zealsun" },
  { key: "zelsun", name: "Zelsun" },
  { key: "znen", name: "Znen" },
  { key: "zongshen", name: "Zongshen" },
  { key: "zontes", name: "Zontes" },
  { key: "zorro", name: "Zorro" },
];

// Her markanın altındaki alt kategoriler (Yol Yardım hariç, o markaya özel
// değil, ortak MotoGo Yol Yardım sistemine yönlendirir)
const SUBCATS = [
  { key: "ozelServis", label: "Özel Servis" },
  { key: "yetkiliServis", label: "Yetkili Servis" },
  { key: "yedekParca", label: "Yedek Parça" },
  { key: "ekspertiz", label: "Ekspertiz", brandFree: true },
  { key: "kiralik", label: "Kiralık Motor", brandFree: true },
  { key: "avantaj", label: "Avantaj", brandFree: true },
];

// Marka + alt kategoriye göre üye firmalar. Şimdilik boş, doldukça eklenir.
// Format: "markaKey_altKategoriKey": [ { name, whatsapp, city, instagram... } ]
let BRAND_FIRMS = {}; // Supabase'den yüklenir (bkz: js/app.js loadMotoGoData)

// Büyük şehirler önce, sonra alfabetik
const CITIES = [
  "İstanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep",
  "Kocaeli", "Mersin",
  "Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ardahan","Artvin","Aydın",
  "Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur",
  "Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ",
  "Erzincan","Erzurum","Eskişehir","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır",
  "Isparta","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri",
  "Kırıkkale","Kırklareli","Kırşehir","Kilis","Kütahya","Malatya","Manisa","Mardin",
  "Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun",
  "Siirt","Sinop","Sivas","Şanlıurfa","Şırnak","Tekirdağ","Tokat","Trabzon","Tunceli",
  "Uşak","Van","Yalova","Yozgat","Zonguldak"
];

// ============================================================================
// MotoGo Yol Yardım — eski siteyle birebir aynı veri, artık bu sayfanın içinde
// ============================================================================
const YARDIM_CATEGORIES = [
  { id: "cekici",      label: "Çekici / Transfer", sub: "Motor çalışmıyor / kaza",  icon: "🚛" },
  { id: "lastik",      label: "Lastik",            sub: "Patlak / hava kaybı",      icon: "🛞" },
  { id: "genel_ariza", label: "Genel Arıza",       sub: "Diğer teknik sorun",       icon: "🔧" }
];

// Kiralık Motor — markadan bağımsız, şehir bazlı firma listesi
let KIRALIK_FIRMS = []; // Supabase'den yüklenir
let EKSPERTIZ_FIRMS = []; // Supabase'den yüklenir

// Avantaj — indirim/kampanya sunan firmalar (sürücü kursu, otel, restoran vb.), markadan bağımsız
let AVANTAJ_FIRMS = []; // Supabase'den yüklenir

let YARDIM_FIRMS = []; // Supabase'den yüklenir

// MotoGo Sözlük — Kılavuz arama motoru için (161 terim)
const SOZLUK_TERIMLERI = [
  { term: "ABS (Anti-blokaj Fren Sistemi)", category: "FREN SİSTEMİ", definition: "Tekerlek hız sensörlerinden gelen verilerle fren basıncını elektronik olarak modüle ederek tekerleğin kilitlenmesini önler. ECU, kayma oranını referans hız ile karşılaştırarak hidrolik ünite üzerinden basıncı ayarlar." },
  { term: "Akü (Battery)", category: "ELEKTRİK SİSTEMİ", definition: "Kimyasal enerjiyi elektrik enerjisine dönüştürerek marş, ateşleme ve aydınlatma devrelerine DC gerilim sağlayan kurşun-asit veya lityum tabanlı depolama ünitesidir. Nominal gerilimi 12V'tur." },
  { term: "Aks (Axle)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Ön ve arka tekerleği şasi veya salıncağa sabitleyen, dönme eksenini oluşturan silindirik millerdir. Yatak (rulman) yuvaları üzerinden radyal yükleri taşır." },
  { term: "Alternatör (Alternator/Stator-Rotor)", category: "ŞARJ SİSTEMİ", definition: "Krank mili üzerine bağlı rotor mıknatıslarının stator sargılarında indüklediği AC gerilimi üretir; regülatör/rektifikör üzerinden DC'ye çevrilip aküyü şarj eder." },
  { term: "Amortisör (Shock Absorber)", category: "SÜSPANSİYON SİSTEMİ", definition: "Yay hareketini sönümlemek amacıyla hidrolik yağın dar orifisler veya şims paketlerinden geçişini kısıtlayan piston-silindir düzeneğidir. Sıkışma ve geri dönüş sönümlemesini ayrı ayrı kontrol eder." },
  { term: "Ateşleme Avansı (Ignition Timing Advance)", category: "ATEŞLEME SİSTEMİ", definition: "Bujinin ateşleme kıvılcımının, pistonun üst ölü noktaya (ÜÖN) ulaşmasından önceki krank açısı cinsinden zamanlamasıdır. Motor devrine ve yüke bağlı olarak ECU tarafından haritalanır." },
  { term: "Ayar Boşluğu (Valve Clearance / Tappet Gap)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "Soğuk motorda kam pabucu ile supap ucu arasında bırakılan, termal genleşmeyi telafi eden boşluktur. Şims veya ayar vidası ile üretici toleransına göre kalibre edilir." },
  { term: "Balata (Brake Pad)", category: "FREN SİSTEMİ", definition: "Fren kaliperi içinde disk yüzeyine sürtünme kuvveti uygulayan, sürtünme malzemesi (organik/sinter) ile kaplı çelik taşıyıcı plakadır." },
  { term: "Basınç Valfi (Pressure Relief Valve)", category: "YAĞLAMA SİSTEMİ", definition: "Yağ pompası çıkış basıncı belirlenen üst sınırı aştığında fazla yağı karter veya emme hattına geri yönlendirerek sistemi aşırı basınca karşı korur." },
  { term: "Biyel Kolu (Connecting Rod)", category: "MOTOR", definition: "Pistonu krank miline bağlayarak doğrusal hareketi dönme hareketine çeviren, küçük ve büyük gözden oluşan mekanik elemandır." },
  { term: "Bijon (Wheel Stud/Lug Bolt)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Tekerlek göbeğini aks veya diferansiyele sabitleyen, belirli sıkma torkuna göre bağlanan dişli saplama veya cıvatadır." },
  { term: "Bilyalı Yatak (Ball Bearing)", category: "MOTOR/ŞANZIMAN", definition: "İç ve dış bilezik arasındaki çelik bilyeler aracılığıyla dönen milin sürtünmesini azaltan, radyal ve eksenel yükleri taşıyan yataklama elemanıdır." },
  { term: "Bowden Kablo (Bowden Cable)", category: "KONTROL SİSTEMİ (GAZ/DEBRİYAJ)", definition: "Esnek bir kılıf içinde kayan çelik tel yardımıyla mekanik hareketi (gaz kolu, debriyaj kolu) uzak bir noktaya ileten kontrol kablosudur." },
  { term: "Bağlantı Kolu (Linkage Arm / Dogbone Link)", category: "SÜSPANSİYON SİSTEMİ (MONO-SHOCK)", definition: "Salıncak ile amortisör arasında yer alarak süspansiyon oranını (progresif karakteristiği) belirleyen mekanik kaldıraç koludur." },
  { term: "Bağlantı Kolu (Linkage Arm / Dogbone Link) SÜSPANSİYON SİSTEMİ", category: "(MONO-SHOCK)", definition: "Salıncak ile amortisör arasında yer alarak süspansiyon oranını (progresif karakteristiği) belirleyen mekanik kaldıraç koludur." },
  { term: "Buji (Spark Plug)", category: "ATEŞLEME SİSTEMİ", definition: "Yüksek gerilim bobininden gelen enerjiyle elektrotlar arasında kıvılcım oluşturarak silindir içindeki hava-yakıt karışımını ateşleyen elemandır." },
  { term: "Cıvata (Bolt)", category: "GENEL BAĞLANTI ELEMANLARI", definition: "Dişli gövdesi ve başı ile iki veya daha fazla parçayı sökülebilir şekilde birleştiren makine elemanıdır. Sıkma torku üretici tarafından Nm cinsinden belirtilir ve tork anahtarı ile kontrol edilir." },
  { term: "Conta (Gasket)", category: "MOTOR", definition: "İki temas yüzeyi arasındaki mikroskobik boşlukları doldurarak basınç, yağ veya soğutma sıvısı kaçağını önleyen sızdırmazlık elemanıdır. Silindir kapağı contası yüksek sıcaklık ve basınca dayanıklı metal veya kompozit malzemeden üretilir." },
  { term: "CDI (Capacitive Discharge Ignition)", category: "ATEŞLEME SİSTEMİ", definition: "Bir kondansatörde biriktirdiği yüksek gerilimi krank pozisyon sinyaline göre ateşleme bobinine anlık boşaltan elektronik ateşleme kontrol ünitesidir. Mekanik platin sistemlerine göre daha kararlı kıvılcım zamanlaması sağlar." },
  { term: "CVT (Continuously Variable Transmission)", category: "ŞANZIMAN/AKTARMA SİSTEMİ", definition: "Sabit vites kademeleri yerine kayış-kasnak mekanizmasıyla çevrim oranını motor devrine göre kademesiz olarak değiştiren otomatik aktarma sistemidir. Genellikle scooter tipi motosikletlerde kullanılır." },
  { term: "Common Rail Enjeksiyon Sistemi", category: "YAKIT ENJEKSİYON SİSTEMİ", definition: "Yakıtın yüksek basınçlı ortak bir hat üzerinden her silindire ayrı enjektörlerle, ECU kontrolünde ve bağımsız zamanlamayla gönderildiği yakıt besleme mimarisidir." },
  { term: "Cam Elyaf (Fiberglass)", category: "GÖVDE/KAPORTA SİSTEMİ", definition: "Reçine ile emdirilmiş cam liflerinden oluşan, hafif ve şekillendirilebilir kompozit gövde/kaporta malzemesidir. Darbe dayanımı düşüktür ancak onarımı ve kalıplanması kolaydır." },
  { term: "Çekiş Kontrolü (Traction Control / TCS)", category: "ELEKTRONİK SÜRÜŞ YARDIM SİSTEMİ", definition: "Arka tekerlek dönüş hızını ön tekerlekle karşılaştırarak aşırı patinajı algılayan ve motor torkunu azaltarak tekerlek tutunmasını geri kazandıran elektronik sistemdir." },
  { term: "Çekiş Kontrolü (Traction Control / TCS) ELEKTRONİK SÜRÜŞ YARDIM", category: "SİSTEMİ", definition: "Arka tekerlek dönüş hızını ön tekerlekle karşılaştırarak aşırı patinajı algılayan ve motor torkunu azaltarak tekerlek tutunmasını geri kazandıran elektronik sistemdir." },
  { term: "Çift Kavrama Şanzıman (Dual Clutch Transmission / DCT)", category: "ŞANZIMAN/AKTARMA SİSTEMİ", definition: "Tek ve çift vitesler için ayrı iki kavramanın kesintisiz güç aktarımı sağlayacak şekilde art arda devreye girdiği otomatik/yarı otomatik vites sistemidir." },
  { term: "Çıkış Mili (Output Shaft)", category: "ŞANZIMAN/AKTARMA SİSTEMİ", definition: "Şanzımandan gelen dönme hareketini zincir, kayış veya kardan mili aracılığıyla arka tekerleğe ileten şanzıman çıkış milidir." },
  { term: "Çamurluk (Fender/Mudguard)", category: "GÖVDE/KAPORTA SİSTEMİ", definition: "Tekerleğin fırlattığı su, çamur ve taşları sürücüden ve mekanik aksamdan uzak tutmak için ön ve arka tekerlek üzerine monte edilen koruyucu paneldir." },
  { term: "Çelik Jant (Steel Rim/Wheel)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Çelik saçtan üretilen, alüminyum alaşımlı jantlara göre daha ağır fakat darbelere karşı daha dayanıklı ve genellikle tel jant uygulamalarında kullanılan tekerlek gövdesidir." },
  { term: "Çark (Gear/Sprocket Wheel)", category: "AKTARMA SİSTEMİ", definition: "Dişli veya zincir dişlisi biçiminde olup güç ve hareketi bir milden diğerine aktaran dönel makine elemanıdır; motor çıkış çarkı ile arka teker çarkı zincir oranını belirler." },
  { term: "Debriyaj (Clutch)", category: "AKTARMA SİSTEMİ", definition: "Motor krank milinden gelen dönme hareketini şanzımana kademeli olarak aktaran veya keserek vites geçişine imkân tanıyan sürtünmeli güç aktarma elemanıdır. Islak çok diskli tip motosikletlerde en yaygın uygulamadır." },
  { term: "Devir (RPM – Revolutions Per Minute)", category: "MOTOR", definition: "Krank milinin dakikadaki tur sayısını ifade eden, motorun çalışma hızını ve yük durumunu gösteren temel performans parametresidir." },
  { term: "Dingil (Axle/Spindle)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Tekerleğin rulmanlar üzerinden döndüğü, ön çatal veya arka salıncağa sabitlenen taşıyıcı mildir." },
  { term: "Disk Fren (Disc Brake)", category: "FREN SİSTEMİ", definition: "Tekerlekle birlikte dönen metal diske, kaliper içindeki balataların hidrolik basınçla sıkıştırılması yoluyla sürtünme kuvveti uygulayarak aracı yavaşlatan fren tertibatıdır." },
  { term: "Dişli Kutusu (Gearbox)", category: "ŞANZIMAN/AKTARMA SİSTEMİ", definition: "İçinde farklı çap oranlarına sahip dişli çiftleri barındıran, motor torkunu farklı vites oranlarında arka teker miline ileten mekanik ünitedir." },
  { term: "Distribütör (Distributor)", category: "ATEŞLEME SİSTEMİ", definition: "Klasik motorlarda, yüksek gerilim akımını doğru zamanlamayla ilgili silindirin bujisine dağıtan mekanik ateşleme dağıtım parçasıdır." },
  { term: "ECU (Engine Control Unit)", category: "ELEKTRONİK ENJEKSİYON SİSTEMİ", definition: "Krank pozisyonu, emme basıncı, gaz kelebeği açısı ve lambda sensörü gibi girdileri işleyerek yakıt enjeksiyon miktarını ve ateşleme zamanlamasını gerçek zamanlı hesaplayan merkezi elektronik denetleyicidir." },
  { term: "Egzoz (Exhaust System)", category: "EGZOZ SİSTEMİ", definition: "Yanma sonucu oluşan atık gazları silindirden alarak susturucu ve katalitik konvertör üzerinden atmosfere yönlendiren, geri basınç yönetimi yapan boru/susturucu tertibatıdır." },
  { term: "Eksantrik Mili (Camshaft)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "Üzerindeki kam profilleri aracılığıyla emme ve egzoz supaplarının açılma-kapanma zamanlamasını ve kaldırma miktarını belirleyen döner mildir; krank miline zincir, kayış veya dişli ile senkronize bağlıdır." },
  { term: "Enjektör (Fuel Injector)", category: "YAKIT ENJEKSİYON SİSTEMİ", definition: "ECU'dan gelen elektrik sinyaliyle açılıp kapanan, yakıtı yüksek basınç altında ince zerrecikler halinde emme manifolduna veya doğrudan silindire püskürten elektromekanik valftir." },
  { term: "Emme Manifoldu (Intake Manifold)", category: "MOTOR", definition: "Hava filtresinden gelen havayı silindir emme portlarına yönlendiren, motor performansını etkileyen geometrik kanal yapısıdır." },
  { term: "Egzoz Valfi (Exhaust Valve)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "Yanma sonrası oluşan atık gazların silindirden egzoz manifolduna tahliye edilmesine izin veren, yüksek sıcaklığa dayanıklı alaşımdan üretilmiş supaptır." },
  { term: "Fren Diski (Brake Disc)", category: "FREN SİSTEMİ", definition: "Tekerlek göbeğine bağlı, balataların sürtünme kuvveti uyguladığı, genellikle delikli veya yivli paslanmaz çelikten üretilen dönel fren yüzeyidir. Isı dağılımını artırmak için havalandırma kanalları içerebilir." },
  { term: "Fren Hidroliği (Brake Fluid / DOT Fluid)", category: "FREN SİSTEMİ", definition: "Fren kumanda pistonundan kaliper pistonuna basıncı ileten, yüksek kaynama noktasına sahip glikol bazlı hidrolik akışkandır. DOT 3/4/5.1 sınıflarına göre nem emme ve kaynama noktası özellikleri değişir." },
  { term: "Far (Headlight)", category: "ELEKTRİK SİSTEMİ", definition: "Sürüş güzergâhını aydınlatan ve aracın karşıdan görünürlüğünü sağlayan, kısa/uzun hüzme fonksiyonlarına sahip aydınlatma ünitesidir." },
  { term: "Flanş (Flange)", category: "GENEL BAĞLANTI ELEMANLARI", definition: "İki milin veya borunun eksenel olarak sabitlenmesi amacıyla kullanılan, cıvata delikleri bulunan disk şeklindeki bağlantı elemanıdır." },
  { term: "Fren Kaliperi (Brake Caliper)", category: "FREN SİSTEMİ", definition: "Fren diskini iki taraftan balatalarla sıkıştıran, içinde hidrolik pistonlar barındıran sabit veya yüzer tip fren gövdesidir." },
  { term: "Fan (Radyatör Fanı / Cooling Fan)", category: "SOĞUTMA SİSTEMİ", definition: "Motor sıcaklığı termostat eşiğini aştığında elektronik olarak devreye giren, radyatör üzerinden hava akışını zorlayarak soğutma sıvısının ısı transferini hızlandıran elektrikli fandır." },
  { term: "Gaz Kelebeği (Throttle Body)", category: "ENJEKSİYON SİSTEMİ", definition: "Sürücünün gaz komutuna göre açılıp kapanan bir valf aracılığıyla motora giren hava miktarını kontrol eden, üzerinde konum sensörü (TPS) barındıran emme elemanıdır." },
  { term: "Gösterge Paneli (Instrument Cluster)", category: "ELEKTRİK SİSTEMİ", definition: "Hız, devir, yakıt seviyesi ve arıza kodlarını sürücüye analog ibre veya dijital ekran üzerinden ileten, ECU ve sensörlerden veri alan gösterge birimidir." },
  { term: "Gidon (Handlebar)", category: "ŞASİ/KONTROL SİSTEMİ", definition: "Ön çatal üst kütüğüne bağlanan, sürücünün direksiyon, fren ve gaz kumandalarını uyguladığı ana kontrol çubuğudur." },
  { term: "Güç Aktarma Organları (Powertrain)", category: "AKTARMA SİSTEMİ", definition: "Motorun ürettiği torku arka tekerleğe ileten debriyaj, şanzıman, zincir/kayış/kardan ve dişli grubundan oluşan mekanik sistemler bütünüdür." },
  { term: "Gaz Kolu (Throttle Grip)", category: "KONTROL SİSTEMİ", definition: "Sürücünün elle döndürerek gaz kelebeğine (veya elektronik gaz sensörüne) komut ilettiği, gidon sağ ucuna monte edilmiş döner kumanda parçasıdır." },
  { term: "Gömlek (Silindir Gömleği / Cylinder Liner)", category: "MOTOR", definition: "Pistonun içinde hareket ettiği, aşınmaya dayanıklı dökme demir veya kaplamalı alüminyumdan üretilen, silindir bloğuna geçirilen iç yüzeydir." },
  { term: "Hava Filtresi (Air Filter)", category: "EMME SİSTEMİ", definition: "Motora giren havadaki toz ve partikülleri tutarak silindir ve piston aşınmasını önleyen, kağıt, köpük veya pamuklu elyaftan üretilen filtrasyon elemanıdır." },
  { term: "Hidrolik Fren Sistemi (Hydraulic Brake System)", category: "FREN SİSTEMİ", definition: "Pascal prensibine dayanarak fren kumanda pistonundaki kuvveti sıkıştırılamayan bir sıvı aracılığıyla kaliper pistonlarına ileten fren mimarisidir." },
  { term: "Hız Sensörü (Speed Sensor)", category: "ELEKTRONİK SİSTEM", definition: "Tekerlek veya şanzıman çıkış milinin dönüş hızını manyetik veya optik prensiple algılayarak ECU, ABS ve gösterge paneline sinyal gönderen sensördür." },
  { term: "Hidrolik Direksiyon Amortisörü (Steering Damper)", category: "SÜSPANSİYON SİSTEMİ", definition: "Ön tekerlekte oluşan ani salınım ve titreşimleri (wobble/tank-slapper) hidrolik sönümleme ile azaltan, gidon ile şasi arasına monte edilen emniyet elemanıdır." },
  { term: "Havalandırma (Karter Havalandırma Sistemi)", category: "MOTOR", definition: "Piston segmanlarından karter içine kaçan yanmamış gazların (blow-by) basıncını tahliye ederek yağ köpürmesini ve sızıntıyı önleyen havalandırma devresidir." },
  { term: "Hidrolik Kaldırıcı (Hydraulic Lifter / Tappet)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "Yağ basıncını kullanarak supap boşluğunu otomatik olarak sıfırlayan, periyodik manuel ayar ihtiyacını ortadan kaldıran kendinden ayarlı itici elemandır." },
  { term: "Islak Kavrama (Wet Clutch)", category: "AKTARMA SİSTEMİ", definition: "Disk paketlerinin motor yağı içinde çalıştığı, yağın hem soğutma hem yağlama sağladığı kavrama tipidir. Kuru kavramaya göre daha yumuşak ve dayanıklı güç aktarımı sunar." },
  { term: "Isı Eşanjörü (Yağ Soğutucu / Oil Cooler)", category: "YAĞLAMA SİSTEMİ", definition: "Motor yağının sıcaklığını, üzerinden geçen hava veya soğutma sıvısı ile değiştirerek düşüren, genellikle petek tipi radyatör benzeri ısı transfer ünitesidir." },
  { term: "Izgara (Radyatör Izgarası / Radiator Grille)", category: "SOĞUTMA SİSTEMİ", definition: "Radyatör peteğini taş ve yabancı cisim darbelerinden koruyan, hava akışına izin veren delikli koruyucu panel veya file yapıdır." },
  { term: "Isı Sensörü (Motor Sıcaklık Sensörü / ECT)", category: "ELEKTRONİK ENJEKSİYON SİSTEMİ", definition: "Soğutma sıvısı veya motor bloğu sıcaklığını ölçerek ECU'ya ileten, yakıt zenginleştirme ve fan devreye alma kararlarında kullanılan termistör tabanlı sensördür." },
  { term: "Isı Kalkanı (Heat Shield)", category: "EGZOZ SİSTEMİ", definition: "Egzoz borusu ve susturucudan yayılan yüksek sıcaklığın sürücüyü, plastik parçaları veya elektrik kablolarını etkilemesini önleyen yalıtımlı metal koruma panelidir." },
  { term: "İğne Yatak (Needle Bearing)", category: "MOTOR/ŞANZIMAN", definition: "İnce ve uzun silindirik iğneler aracılığıyla yük taşıyan, dar radyal alanlarda yüksek taşıma kapasitesi sağlayan yataklama elemanıdır; genellikle şanzıman dişli milleri ve biyel küçük gözünde kullanılır." },
  { term: "İmmobilizer (Immobilizer)", category: "GÜVENLİK SİSTEMİ", definition: "Kontak anahtarındaki entegre çipin ECU tarafından tanınmadığı durumda ateşleme veya yakıt beslemesini elektronik olarak devre dışı bırakan hırsızlık önleme sistemidir." },
  { term: "İndüksiyon Bobini (Ateşleme Bobini / Ignition Coil)", category: "ATEŞLEME SİSTEMİ", definition: "Akü geriliminden buji ucunda kıvılcım oluşturacak yüksek voltajı (10-30 kV) elektromanyetik indüksiyon prensibiyle üreten step-up transformatördür." },
  { term: "İzolasyon (Kablo İzolasyonu / Wiring Insulation)", category: "ELEKTRİK SİSTEMİ", definition: "Elektrik kablolarının iletken çekirdeğini nem, sürtünme ve kısa devreye karşı koruyan, genellikle PVC veya poliolefin bazlı dış kaplama malzemesidir." },
  { term: "İtme Çubuğu (Push Rod)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "OHV tip motorlarda eksantrik milinin hareketini külbütöre ileten, kam pabucu ile külbütör kolu arasında yer alan ince mekanik çubuktur." },
  { term: "Jant (Rim)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Lastiğin oturduğu, tel veya döküm alaşımdan üretilen, tekerleğin dış çevresel taşıyıcı halkasıdır." },
  { term: "Jant Kapağı (Wheel Hub Cap)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Jant göbeğindeki rulman ve aks bağlantı noktasını toz, su ve kirden koruyan estetik/koruyucu kapaktır." },
  { term: "Jikle (Choke Valve)", category: "KARBÜRATÖR SİSTEMİ", definition: "Soğuk motor çalıştırmasını kolaylaştırmak amacıyla emme havasını kısarak karışımı geçici olarak zenginleştiren karbüratör kontrol valfidir." },
  { term: "Jeneratör (Generator)", category: "ŞARJ SİSTEMİ", definition: "Mekanik enerjiyi elektrik enerjisine dönüştüren, klasik motosikletlerde alternatör öncesi kullanılan doğru veya alternatif akım üretim ünitesidir." },
  { term: "Jantlama (Wheel Truing / Lacing)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Tel jantlarda ispit gerginliklerinin ayarlanmasıyla jantın eksenel ve radyal salgısının toleranslar dahiline çekilmesi işlemidir." },
  { term: "Karbüratör (Carburetor)", category: "YAKIT SİSTEMİ", definition: "Venturi etkisiyle emme havasına belirli oranda benzin karıştırarak yanabilir hava-yakıt karışımı hazırlayan mekanik yakıt besleme ünitesidir." },
  { term: "Krank Mili (Crankshaft)", category: "MOTOR", definition: "Biyel kolu aracılığıyla pistonun doğrusal hareketini alarak dönme hareketine çeviren, motor gücünün dışarıya aktarıldığı ana çıkış milidir." },
  { term: "Kasnak (Pulley)", category: "AKTARMA SİSTEMİ", definition: "Kayış ile güç aktarımı yapılan sistemlerde (CVT), kayışın oturduğu ve çapı değişerek çevrim oranını belirleyen konik veya sabit çaplı disktir." },
  { term: "Kavrama Baskı Plakası (Clutch Pressure Plate)", category: "AKTARMA SİSTEMİ", definition: "Yaylar aracılığıyla kavrama disklerini volan veya kavrama sepetine bastırarak sürtünme yoluyla güç aktarımını sağlayan baskı elemanıdır." },
  { term: "Katalitik Konvertör (Catalytic Converter)", category: "EGZOZ SİSTEMİ", definition: "Egzoz gazlarındaki CO, HC ve NOx bileşenlerini platin/paladyum/rodyum kaplı seramik yapı üzerinde kimyasal reaksiyonla daha az zararlı bileşenlere dönüştüren emisyon kontrol ünitesidir." },
  { term: "Karter (Crankcase)", category: "MOTOR", definition: "Krank milini, biyel kollarını ve genellikle şanzıman grubunu içinde barındıran, motor yağı haznesi görevi de gören ana motor gövdesidir." },
  { term: "Lastik (Tire)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Jant üzerine monte edilen, iç basınçlı hava ile yol tutuşu, konfor ve yük taşıma fonksiyonlarını sağlayan kauçuk esaslı temas elemanıdır." },
  { term: "Lastik Valfi (Tire Valve)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Lastik iç hava basıncının doldurulmasına izin veren ve tek yönlü sübap mekanizmasıyla basıncın kaçmasını önleyen küçük valf elemanıdır." },
  { term: "Lastik Basınç Sensörü (TPMS)", category: "ELEKTRONİK SİSTEM", definition: "Lastik iç basıncını ve sıcaklığını gerçek zamanlı izleyerek düşük basınç durumunda sürücüyü gösterge paneli üzerinden uyaran elektronik sensör sistemidir." },
  { term: "Lastik Basınç Sensörü (TPMS)", category: "ELEKTRONİK SİSTEM", definition: "Lastik iç basıncını ve sıcaklığını gerçek zamanlı izleyerek düşük basınç durumunda sürücüyü gösterge paneli üzerinden uyaran elektronik sensör sistemidir." },
  { term: "Lambda Sensörü (O2 Sensörü)", category: "ENJEKSİYON/EGZOZ SİSTEMİ", definition: "Egzoz gazındaki artık oksijen miktarını ölçerek hava-yakıt karışımının stokiyometrik orana (λ=1) yakınlığı hakkında ECU'ya geri bildirim sağlayan sensördür." },
  { term: "Limit Şalteri (Vites Boşta / Yan Sehpa Anahtarı)", category: "ELEKTRİK/GÜVENLİK SİSTEMİ", definition: "Vites boşta değilken veya yan sehpa açıkken marş ya da ateşleme devresini güvenlik amacıyla kesen konum algılama anahtarıdır." },
  { term: "Marş Motoru (Starter Motor)", category: "ELEKTRİK SİSTEMİ", definition: "Akü enerjisiyle çalışan, dişli aracılığıyla volana veya krank miline bağlanarak motoru ilk çalıştırma devrine kadar döndüren elektrik motorudur." },
  { term: "Motor Bloğu (Engine Block)", category: "MOTOR", definition: "Silindir, krank mili yatakları ve yağ kanallarını barındıran, motorun ana taşıyıcı döküm gövdesidir." },
  { term: "Egzoz Manifoldu (Exhaust Manifold)", category: "EGZOZ SİSTEMİ", definition: "Silindir egzoz portlarından çıkan atık gazları tek bir egzoz borusunda toplayan, ısıya dayanıklı döküm veya paslanmaz çelik kollektördür." },
  { term: "Merkezkaç Kavraması (Centrifugal Clutch)", category: "AKTARMA SİSTEMİ", definition: "Motor devrine bağlı merkezkaç kuvvetiyle otomatik olarak bağlanıp ayrılan, debriyaj kolu gerektirmeyen otomatik kavrama tipidir; scooterlarda yaygındır." },
  { term: "Motor Yağı (Engine Oil)", category: "YAĞLAMA SİSTEMİ", definition: "Hareketli parçalar arasındaki sürtünmeyi azaltan, ısı transferi ve kir taşıma görevi de üstlenen, viskozite sınıfı (SAE) ile tanımlanan yağlama akışkanıdır." },
  { term: "Manyeto (Magneto)", category: "ATEŞLEME SİSTEMİ", definition: "Akü gerektirmeden, dönen mıknatıslar ile doğrudan yüksek gerilim üreten klasik mekanik ateşleme jeneratörüdür." },
  { term: "Nötr Sensörü (Neutral Switch)", category: "ŞANZIMAN/ELEKTRİK SİSTEMİ", definition: "Şanzımanın boşta konumda olduğunu algılayarak gösterge panelindeki nötr ikaz lambasını yakan ve güvenlik devrelerine sinyal ileten konum sensörüdür." },
  { term: "Nihai Tahrik (Final Drive)", category: "AKTARMA SİSTEMİ", definition: "Şanzıman çıkışından gelen gücü son oranla arka tekerleğe ileten zincir-dişli, kayış-kasnak veya kardan-pinyon dişli grubudur." },
  { term: "Enjektör Nozulu (Injector Nozzle)", category: "YAKIT ENJEKSİYON SİSTEMİ", definition: "Enjektör ucunda yer alan, yakıtı belirli bir sprey açısı ve damlacık boyutunda atomize ederek püskürten hassas delikli parçadır." },
  { term: "Negatif Kutup Başı (Akü Eksi Terminali)", category: "ELEKTRİK SİSTEMİ", definition: "Akünün şasi topraklamasına bağlanan, elektrik devresinin dönüş yolunu oluşturan eksi kutuplu bağlantı noktasıdır." },
  { term: "Su Geçirmez Konnektör (Waterproof Connector)", category: "ELEKTRONİK SİSTEM", definition: "İçindeki kauçuk contalar sayesinde nem ve su girişine karşı korunan, elektronik sensör ve kablo demeti bağlantılarında kullanılan konnektör tipidir." },
  { term: "Orta Ayak (Center Stand)", category: "ŞASİ SİSTEMİ", definition: "Motosikleti her iki tekerleği de yerden keserek dik ve dengeli biçimde park etmeye yarayan, bakım işlemlerini kolaylaştıran katlanır destek mekanizmasıdır." },
  { term: "Ön Çatal (Front Fork)", category: "SÜSPANSİYON SİSTEMİ", definition: "Ön tekerleği taşıyan, içinde yay ve hidrolik sönümleme ünitesi barındıran teleskopik süspansiyon borularıdır; direksiyon hareketini de yönlendirir." },
  { term: "O-Ring (Conta Halkası)", category: "GENEL SIZDIRMAZLIK ELEMANLARI", definition: "Dairesel kesitli, kauçuk veya sentetik elastomerden üretilen, iki parça arasındaki radyal veya eksenel sızdırmazlığı sağlayan halka contadır." },
  { term: "Otomatik Dekompresyon Valfi (Auto-Decompression Valve)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "Marş anında düşük devirde egzoz supabını kısmen açık tutarak silindir içi kompresyonu azaltan ve ilk çalıştırmayı kolaylaştıran mekanizmadır." },
  { term: "Oransal Basınç Valfi (Proportioning Valve)", category: "FREN SİSTEMİ", definition: "Ön ve arka fren hatları arasındaki hidrolik basıncı, yük transferine göre dengeleyerek arka tekerlek kilitlenmesini geciktiren fren valfidir." },
  { term: "Ölü Nokta (Dead Center - ÜÖN/AÖN)", category: "MOTOR", definition: "Pistonun silindir içinde ulaştığı en üst (ÜÖN) veya en alt (AÖN) konum noktasıdır; krank açısı ve zamanlama ölçümlerinde referans olarak kullanılır." },
  { term: "Ölü Nokta (Dead Center - ÜÖN/AÖN)", category: "MOTOR", definition: "Pistonun silindir içinde ulaştığı en üst (ÜÖN) veya en alt (AÖN) konum noktasıdır; krank açısı ve zamanlama ölçümlerinde referans olarak kullanılır." },
  { term: "Ölçü Çubuğu (Dipstick)", category: "YAĞLAMA SİSTEMİ", definition: "Karter içindeki motor yağı seviyesinin görsel olarak kontrol edilmesini sağlayan, üzerinde min/max işaretleri bulunan çubuktur." },
  { term: "Örgülü Hortum (Braided Hose)", category: "FREN/YAKIT SİSTEMİ", definition: "İç kauçuk yapıyı çelik veya kevlar örgü ile güçlendirerek yüksek basınç altında şişmeyi azaltan, fren hissini iyileştiren hortum tipidir." },
  { term: "Öngerilim (Preload)", category: "SÜSPANSİYON SİSTEMİ", definition: "Yayın sükunet konumunda önceden sıkıştırılma miktarını ifade eden, sürücü ağırlığına göre süspansiyon sertliğini ve sag değerini ayarlamak için kullanılan parametredir." },
  { term: "Piston (Piston)", category: "MOTOR", definition: "Silindir içinde doğrusal hareket ederek yanma basıncını biyel koluna ileten, alüminyum alaşımdan üretilmiş hareketli motor elemanıdır." },
  { term: "Piston Segmanı (Piston Ring)", category: "MOTOR", definition: "Piston ile silindir gömleği arasındaki sızdırmazlığı sağlayan, kompresyon kaybını önleyen ve yağ sıyırma görevi gören ince metal halkalardır." },
  { term: "Yakıt Pompası (Fuel Pump)", category: "YAKIT SİSTEMİ", definition: "Yakıt deposundan enjeksiyon rampasına gerekli basınçta (genellikle 3-5 bar) yakıt gönderen elektrikli veya mekanik pompadır." },
  { term: "Yağ Pompası (Oil Pump)", category: "YAĞLAMA SİSTEMİ", definition: "Karterdeki yağı emerek motor içindeki yağlama noktalarına basınçlı olarak dağıtan, genellikle dişli veya rotor tipi pozitif deplasmanlı pompadır." },
  { term: "Platin (Contact Breaker Points)", category: "ATEŞLEME SİSTEMİ", definition: "Klasik ateşleme sistemlerinde ateşleme bobini birincil devresini mekanik olarak açıp kapatarak kıvılcım oluşumunu tetikleyen temas noktalarıdır." },
  { term: "Progresif Yay (Progressive Spring)", category: "SÜSPANSİYON SİSTEMİ", definition: "Sarım aralığı değişken olduğundan sıkışma arttıkça yay sertliği kademeli olarak artan, hem konfor hem darbe emme performansı sunan yay tipidir." },
  { term: "Radyatör (Radiator)", category: "SOĞUTMA SİSTEMİ", definition: "Motor soğutma sıvısının taşıdığı ısıyı, ince kanallar ve kanatçıklar aracılığıyla geçen hava akımına aktararak sıvı sıcaklığını düşüren ısı eşanjörüdür." },
  { term: "Regülatör/Rektifikör (Regulator/Rectifier)", category: "ŞARJ SİSTEMİ", definition: "Alternatörden gelen değişken AC gerilimi DC'ye çeviren ve akü şarj gerilimini (yaklaşık 14V) sabit tutarak sistemi aşırı gerilimden koruyan elektronik ünitedir." },
  { term: "Rulman (Bearing)", category: "GENEL MEKANİK ELEMANLAR", definition: "Dönen bir milin sabit bir gövde içinde düşük sürtünmeyle hareket etmesini sağlayan, bilyalı, makaralı veya iğneli yataklama elemanıdır." },
  { term: "Röle (Relay)", category: "ELEKTRİK SİSTEMİ", definition: "Düşük akımlı bir kontrol sinyaliyle yüksek akımlı bir devreyi elektromıknatıs yardımıyla açıp kapatan elektromekanik anahtarlama elemanıdır." },
  { term: "Zincir Ayarı (Chain/Wheel Alignment)", category: "AKTARMA/ŞASİ SİSTEMİ", definition: "Arka tekerleğin şasi ekseniyle paralelliğini ve zincir gerginliğini üretici toleransına göre ayarlama işlemidir; yanlış ayar erken aşınmaya yol açar." },
  { term: "Rekor/Banjo Cıvatası (Banjo Bolt)", category: "FREN SİSTEMİ", definition: "İçi delik açılmış, hidrolik fren hortumunu kaliper veya pompa gövdesine bağlayan, sızdırmazlık için bakır pul kullanılan özel bağlantı cıvatasıdır." },
  { term: "Silindir (Cylinder)", category: "MOTOR", definition: "İçinde pistonun yukarı-aşağı hareket ettiği, yanma odasının alt sınırını oluşturan silindirik motor boşluğudur." },
  { term: "Supap (Valve)", category: "MOTOR (SUPAP SİSTEMİ)", definition: "Emme ve egzoz portlarını kam profiline senkronize şekilde açıp kapatarak silindire hava-yakıt karışımı girişini ve egzoz gazı çıkışını kontrol eden elemandır." },
  { term: "Salıncak (Swingarm)", category: "ŞASİ/SÜSPANSİYON SİSTEMİ", definition: "Arka tekerleği taşıyan, ön ucundan şasiye mafsallı olarak bağlanan ve arka amortisör aracılığıyla düşey hareketi sönümleyen taşıyıcı koldur." },
  { term: "Stator (Stator Sargısı)", category: "ŞARJ SİSTEMİ", definition: "Alternatörün sabit gövdesinde yer alan, üzerinden geçen dönel mıknatıs alanı sayesinde elektrik akımı indüklenen bakır sargı grubudur." },
  { term: "Soğutma Sıvısı (Coolant)", category: "SOĞUTMA SİSTEMİ", definition: "Su ve antifriz (etilen glikol) karışımından oluşan, motor çalışma sıcaklığını güvenli aralıkta tutan ve donma/kaynama noktalarını iyileştiren ısı taşıyıcı akışkandır." },
  { term: "Sıkıştırma Oranı (Compression Ratio)", category: "MOTOR", definition: "Pistonun alt ölü noktadaki toplam silindir hacminin, üst ölü noktadaki yanma odası hacmine oranıdır; motorun verimini ve yakıt oktan ihtiyacını belirleyen temel tasarım parametresidir." },
  { term: "Şanzıman (Gearbox/Transmission)", category: "AKTARMA SİSTEMİ", definition: "Motor torkunu farklı dişli oranları aracılığıyla ihtiyaca göre çoğaltıp azaltan, sürüş koşullarına uygun hız-tork dengesini sağlayan mekanik ünitedir." },
  { term: "Şasi (Frame/Chassis)", category: "ŞASİ SİSTEMİ", definition: "Motoru, süspansiyonu, tekerlekleri ve gövde parçalarını birbirine bağlayan, sürüş dinamiklerini ve yapısal rijitliği belirleyen ana taşıyıcı iskelettir." },
  { term: "Şarj Lambası (Charge Warning Light)", category: "ELEKTRİK SİSTEMİ", definition: "Şarj sisteminde arıza veya yetersiz şarj gerilimi tespit edildiğinde gösterge panelinde yanan, sürücüyü uyaran ikaz lambasıdır." },
  { term: "Şamandıra (Float Valve)", category: "KARBÜRATÖR SİSTEMİ", definition: "Karbüratör yakıt haznesindeki benzin seviyesini, yüzen bir şamandıra ile mekanik olarak sabit tutan ve taşmayı önleyen seviye kontrol valfidir." },
  { term: "Şaft Tahrik (Shaft Drive)", category: "AKTARMA SİSTEMİ", definition: "Gücü zincir yerine kapalı bir kardan mili ve konik dişli grubu aracılığıyla arka tekerleğe ileten, bakım gereksinimi düşük tahrik mimarisidir." },
  { term: "Triger Kayışı/Zinciri (Timing Chain/Belt)", category: "MOTOR", definition: "Krank milinin dönme hareketini eksantrik miline senkronize biçimde ileterek supap zamanlamasının krank pozisyonuyla uyumlu kalmasını sağlayan aktarma elemanıdır." },
  { term: "Tekerlek (Wheel)", category: "ŞASİ/TEKERLEK SİSTEMİ", definition: "Jant, lastik, rulman ve akstan oluşan, aracın yolla temasını ve hareketini sağlayan döner taşıyıcı ünitedir." },
  { term: "Termostat (Thermostat)", category: "SOĞUTMA SİSTEMİ", definition: "Soğutma sıvısı sıcaklığına duyarlı bir balmumu eleman aracılığıyla radyatör devresini açıp kapatarak motorun hızla optimum çalışma sıcaklığına ulaşmasını sağlayan valftir." },
  { term: "Transistörlü Ateşleme Sistemi (TCI)", category: "ATEŞLEME SİSTEMİ", definition: "Mekanik platin yerine yarı iletken transistörler kullanarak ateşleme birincil devresini kesen, daha kararlı ve bakımsız çalışan elektronik ateşleme sistemidir." },
  { term: "Turboşarj (Turbocharger)", category: "EMME/EGZOZ SİSTEMİ", definition: "Egzoz gazı enerjisiyle döndürülen bir türbinin, aynı mile bağlı kompresör çarkı aracılığıyla emme havasını basınçlandırarak motor hacimsel verimini artırdığı zorlamalı emme ünitesidir." },
  { term: "Teşhis Konnektörü (Diagnostic Connector / OBD)", category: "ELEKTRONİK SİSTEM", definition: "Arıza teşhis cihazlarının ECU ile iletişim kurarak arıza kodlarını okumasına ve canlı sensör verilerini izlemesine imkân tanıyan standart bağlantı noktasıdır." },
  { term: "Teşhis Konnektörü (Diagnostic Connector / OBD)", category: "ELEKTRONİK SİSTEM", definition: "Arıza teşhis cihazlarının ECU ile iletişim kurarak arıza kodlarını okumasına ve canlı sensör verilerini izlemesine imkân tanıyan standart bağlantı noktasıdır." },
  { term: "Uyarı Lambası (Warning Light)", category: "ELEKTRİK SİSTEMİ", definition: "Motor arızası, yağ basıncı düşüklüğü veya ABS gibi durumları sürücüye görsel olarak bildiren, gösterge panelinde yer alan ikaz lambasıdır." },
  { term: "Uzun Far (High Beam)", category: "ELEKTRİK SİSTEMİ", definition: "Gece sürüşünde uzak mesafeyi güçlü ve geniş açılı ışıkla aydınlatan, karşı trafik varlığında kapatılması gereken far modudur." },
  { term: "Uzaktan Kumanda/Anahtar (Remote Key / Fob)", category: "ELEKTRİK/GÜVENLİK SİSTEMİ", definition: "RF sinyali ile immobilizer ve alarm sistemine kimlik doğrulaması gönderen, kontak açma iznini uzaktan ileten elektronik anahtar birimidir." },
  { term: "Uyarı Üçgeni Bağlantı Soketi (Auxiliary Power Socket)", category: "ELEKTRİK SİSTEMİ", definition: "Ek aksesuar veya elektronik cihazların araç akülü beslemeye bağlanabilmesi için şaside sağlanan yardımcı elektrik çıkış noktasıdır." },
  { term: "Üst Ölü Nokta (Top Dead Center / ÜÖN)", category: "MOTOR", definition: "Pistonun silindir içinde krank miline en uzak, kompresyon veya egzoz strokunun sonunda ulaştığı üst konum noktasıdır; ateşleme zamanlaması bu noktaya göre referanslanır." },
  { term: "Üniversal Mafsal (Cardan/Universal Joint)", category: "AKTARMA SİSTEMİ", definition: "Şaft tahrikli sistemlerde, açılı konumdaki iki mil arasında dönme hareketini kesintisiz aktarmaya imkân tanıyan mafsallı bağlantı elemanıdır." },
  { term: "Üfleme Valfi (Blow-off/Wastegate Valve)", category: "TURBO/EGZOZ SİSTEMİ", definition: "Turbolu sistemlerde emme basıncı güvenlik sınırını aştığında fazla basıncı tahliye ederek turbo ve motoru aşırı basınçtan koruyan valftir." },
  { term: "Üretim/Şasi Plakası (VIN Plate)", category: "ŞASİ SİSTEMİ", definition: "Aracın benzersiz şasi numarasını (VIN), üretim yılını ve teknik özelliklerini içeren, yasal kimliklendirme amacıyla şasiye sabitlenmiş metal plakadır." },
  { term: "Vites Kolu (Gear Shift Lever)", category: "AKTARMA/KONTROL SİSTEMİ", definition: "Sürücünün ayakla hareket ettirerek şanzıman içindeki vites çatallarını konumlandırdığı, vites değişimini tetikleyen dış kumanda koludur." },
  { term: "Vites Pedalı (Shift Pedal)", category: "KONTROL SİSTEMİ", definition: "Vites kolunun sürücü ayağıyla temas ettiği, yukarı/aşağı basılarak vites değiştirmeyi sağlayan uç parçasıdır." },
  { term: "Volan (Flywheel)", category: "MOTOR", definition: "Krank miline bağlı, dönme hareketinin ataletini artırarak motor devrindeki dalgalanmaları (tork darbelerini) yumuşatan ağır dönel kütledir." },
  { term: "Yakıt Vanası (Fuel Petcock)", category: "YAKIT SİSTEMİ", definition: "Yakıt deposundan karbüratöre giden benzin akışını açan, kapatan veya rezerve konumuna alan manuel ya da vakumla çalışan musluk valfidir." },
  { term: "Vakum Hortumu (Vacuum Hose)", category: "EMME/ENJEKSİYON SİSTEMİ", definition: "Emme manifoldundaki negatif basıncı MAP sensörü, yakıt vanası veya diğer vakum kumandalı elemanlara ileten esnek bağlantı hortumudur." },
  { term: "Yay (Spring)", category: "SÜSPANSİYON/GENEL MEKANİK", definition: "Elastik deformasyon yoluyla enerji depolayan ve serbest bırakan, darbeleri sönümleme ve mekanik ön yükleme amacıyla kullanılan sarmal veya yaprak şeklindeki elemandır." },
  { term: "Yağ Filtresi (Oil Filter)", category: "YAĞLAMA SİSTEMİ", definition: "Motor yağındaki metal talaşı, kurum ve partikülleri tutarak yağın temiz kalmasını ve yatak/silindir aşınmasının azalmasını sağlayan filtrasyon ünitesidir." },
  { term: "Yakıt Deposu (Fuel Tank)", category: "YAKIT SİSTEMİ", definition: "Motosikletin yakıt ihtiyacını karşılamak üzere benzini basınca ve sızdırmazlığa uygun şekilde depolayan, genellikle çelik veya plastik gövdeli hazneddir." },
  { term: "Yağ Keçesi (Oil Seal)", category: "MOTOR/GENEL MEKANİK", definition: "Dönen bir mil ile sabit gövde arasındaki boşluktan yağ sızıntısını önleyen, kauçuk dudaklı ve genellikle yaylı bilezikli dinamik sızdırmazlık elemanıdır." },
  { term: "Yastıklı Kaplin (Cush Drive Rubber)", category: "AKTARMA SİSTEMİ", definition: "Arka teker göbeği ile zincir dişlisi arasına yerleştirilen, ani tork darbelerini kauçuk elemanlar aracılığıyla sönümleyerek şanzımanı ve zinciri koruyan yastıklama düzeneğidir." },
  { term: "Yay Sertliği (Spring Rate)", category: "SÜSPANSİYON SİSTEMİ", definition: "Yayın birim sıkışma mesafesi başına ürettiği kuvveti (N/mm) ifade eden, süspansiyon sertliğinin temel mühendislik parametresidir." },
  { term: "Zincir (Chain)", category: "AKTARMA SİSTEMİ", definition: "Motor gücünü çıkış dişlisinden arka teker dişlisine ileten, birbirine mafsallı baklalardan oluşan, O-ring veya X-ring contalı dayanıklı tahrik elemanıdır." },
  { term: "Zincir Gergisi (Chain Tensioner)", category: "AKTARMA SİSTEMİ", definition: "Zincirin sarkmasını önleyerek doğru gerginlikte kalmasını sağlayan, yaylı veya hidrolik mekanizmalı ayar elemanıdır." },
  { term: "Zamanlama Ayarı (Valve Timing)", category: "MOTOR", definition: "Supapların krank mili açısına göre açılma ve kapanma anlarının, motor verimini optimize edecek şekilde eksantrik mili ile senkronize edilmesi işlemidir." },
  { term: "Zemin Yüksekliği (Ground Clearance)", category: "ŞASİ SİSTEMİ", definition: "Motosikletin en alt sabit noktası ile yol yüzeyi arasındaki dikey mesafedir; arazi kabiliyeti ve viraj yatış açısını doğrudan etkileyen şasi parametresidir." },
  { term: "Zar/Diyafram (Diaphragm)", category: "KARBÜRATÖR/YAKIT SİSTEMİ", definition: "Vakum farkına göre esneyerek hareket ileten, CV tip karbüratörlerde piston/iğne konumunu emme vakumuna göre otomatik ayarlayan esnek membran parçasıdır." },
];